action_id: trunk-share-with-everyone
date: 2024-12-04 21:32:37
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\DHZGf.yaml for details.
  error_path: D:\PathwaysGI\pgi-logging\.trunk\out\DHZGf.yaml
timestamp: 1733347957
full_timestamp:
  nanos: 891588000
  seconds: 1733347957
trunk_version: 1.22.2
